version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    AWS_REGION: ap-south-1
    ECR_REPO: simple-node-app
    ACCOUNT_ID: 979566283645

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing npm dependencies...
      - npm install

  pre_build:
    commands:
      - echo Compiling TypeScript...
      - npm run build
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo Generating imagedefinitions.json for CodeDeploy...
      - printf '[{"name":"simple-node-app","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
    - scripts/**/*
